---
# Project Information
site_name: "OMEGA-Py"
site_url: "https://astcherbinine.github.io/omegapy"
site_author: "Aurélien Stcherbinine"
site_description: "OMEGA-Py: Python tools for OMEGA data"

# Repository information
repo_name: "AStcherbinine/omegapy"
repo_url: "https://github.com/AStcherbinine/omegapy"
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2023 Aurélien Stcherbinine

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    view: material/eye
  logo: img/logo_omegapy.svg
  favicon: img/favicon_omegapy.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
      primary: red
      accent: orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: red
      accent: orange
  features:
    - navigation.instant
    - navigation.tabs
  language: en

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_api_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [omegapy]
          options:
            docstring_style: numpy
            docstring_section_style: table
  - literate-nav:
      nav_file: SUMMARY.md

# Footer
extra:
  #history_buttons: false
  version: v2.4
  #nav_links:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AStcherbinine
      name: AStcherbinine on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Astrorelien
      name: Astrorelien on Twitter
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Aurelien-Stcherbinine
      name: Aurélien Stcherbinine on ResearchGate
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aurelien-stcherbinine/
      name: Aurélien Stcherbinine on LinkedIn
    #- icon: fontawesome/regular/globe
    #  link: https://aurelien.stcherbinine.net/
    #  name: Aurélien Stcherbinine personal page

# Page tree
nav:
  - Home: index.md
  #- 'User Guide':
    #- 'Getting Started': 'getting_started.md'
    #- 'Examples': examples.md
  #- About: about.md
  - Readme: readme.md
  - Code Reference: reference/

