---
# Project Information
site_name: "OMEGA-Py"
site_url: "https://astcherbinine.github.io/omegapy"
site_author: "Aurélien Stcherbinine"
site_description: "OMEGA-Py: Python tools for OMEGA data"

# Repository information
repo_name: "AStcherbinine/omegapy"
repo_url: "https://github.com/AStcherbinine/omegapy"
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2023 Aurélien Stcherbinine

# Configuration
theme:
  name: custommill
  search_index_only: true
  include_search_page: true
  home: usage
  main_color: "#bb0000"
  gray: "#d0d0d0"
  lighter_gray: "#eeeeee"
  date_time_format: "%Y-%m-%d %H:%M:%S %Z"
  toc_depth: 2
#  icon:
#    repo: fontawesome/brands/github
#    view: material/eye
#  features:
#    - navigation.instant
#    - navigation.tabs
#  language: en

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_api_pages.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [omegapy]
  - literate-nav:
      nav_file: SUMMARY.md

# Footer
extra:
  history_buttons: false
  version: v2.4
  nav_links:
#  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AStcherbinine
      name: AStcherbinine on GitHub

# Page tree
nav:
  - Home: index.md
  #- 'User Guide':
    #- 'Getting Started': 'getting_started.md'
    #- 'Examples': examples.md
  #- About: about.md
  - Code Reference: reference/

